INSERT INTO Categoria (nome, descrizione)
VALUES 
  ('shonen', 'Genere di manga e anime indirizzato principalmente ai ragazzi adolescenti'),
  ('azione', 'Opere caratterizzate da molte scene di combattimento e azione'),
  ('dramma', 'Storie che enfatizzano gli elementi emotivi e il conflitto interpersonale'),
  ('supereroi', 'Rappresentazione di personaggi con superpoteri e la loro lotta contro il male'),
  ('psicologico', 'Opere che esplorano la psicologia dei personaggi e le loro motivazioni'),
  ('seinen', 'Manga e anime rivolti a un pubblico adulto, in particolare giovani uomini'),
  ('dark fantasy', 'Sottogenere del fantasy che presenta temi oscuri e atmosfere cupe'),
  ('mistero', 'Storie incentrate sulla risoluzione di un enigma o un crimine'),
  ('paranormale', 'Includono elementi sovrannaturali o paranormali'),
  ('sovrannaturale', 'Riguardano eventi o fenomeni che sfidano le leggi della natura'),
  ('commedia', 'Opere che hanno l\'intento di far ridere e divertire il pubblico'),
  ('thriller', 'Opere caratterizzate da suspense e tensione narrativa'),
  ('soprannaturale', 'Coinvolgono elementi sovrannaturali o magici'),
  ('avventura', 'Storie che coinvolgono viaggi, esplorazioni e avventure'),
  ('fantasy', 'Opere che coinvolgono elementi magici, creature e mondi immaginari'),
  ('shojo', 'Genere di manga e anime indirizzato principalmente alle ragazze adolescenti'),
  ('romantico', 'Storie incentrate sulle relazioni romantiche tra i personaggi'),
  ('parodia', 'Imitazione o presa in giro di un genere, opera o stile'),
  ('sport', 'Storie incentrate su attività sportive e competizioni'),
  ('horror', 'Opere che cercano di suscitare paura, terrore o disgusto nel pubblico'),
  ('mecha', 'Opere con protagonisti robotici o veicoli meccanici'),
  ('western', 'Ambientate nell\'epoca del selvaggio west americano'),
  ('romance', 'Storie incentrate sulla relazione amorosa tra i personaggi'),
  ('distopico', 'Rappresentano società future in cui esiste una grande oppressione e sottoproduzione'),
  ('politico', 'Storie che coinvolgono temi e intrighi politici'),
  ('zombie', 'Coinvolgono zombie o morti viventi come elemento principale'),
  ('steampunk', 'Ambientate in un\'epoca in cui la tecnologia a vapore è predominante'),
  ('mitologia', 'Opere basate su miti e leggende'),
  ('orrore', 'Opere che cercano di suscitare paura e terrore nel pubblico'),
  ('post apocalittico', 'Ambientate in un mondo dopo una catastrofe'),
  ('DEFAULT', 'Descrizione mancante');
